openapi: 3.0.0
info:
  title: Cheat Buster API
  version: 1.0.0
  description: API to check if someone exists in the dating profile database

servers:
  - url: http://localhost:3000

paths:
  /api/search:
    get:
      summary: Search for a user by email
      description: Check if a user exists in the dating database by their email.
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            format: email
          description: Email address to search for
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid email format
        404:
          description: User not found
        500:
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        age:
          type: number
        city:
          type: string
        picture:
          type: string
